import { useEffect } from "react";

const TechnicalCommittee = () => {
  useEffect(() => {
    function scrollToTop() {
      window.scrollTo({
        top: 0,
        behavior: "auto",
      });
    }
    scrollToTop();
  }, []);
  const csvData = [
    ["S.No", "Name", "Designation", "Affiliation", "Mail ID"],
    [
      "1",
      "Dr. Kulvinder Singh",
      "Assistant Professor",
      "Baba Farid College of Engineering & Technology, Bathinda, Punjab",
      "Kulvinder.hundal@gmail.com",
    ],
    [
      "2",
      "Dr. Ankur Goyal",
      "Associate Professor",
      "Symbiosis Institute of Technology, Pune",
      "ankur.goyal@sitpune.edu.in",
    ],
    [
      "3",
      "Dr. Mohammad Ishrat",
      "Associate Professor",
      "Department of CSE, Vaddeshwaram, Guntur",
      "ishratzgzp@gmail.com",
    ],
    [
      "4",
      "Dr. Shakti Kundu",
      "Associate Professor",
      "BML Munjal University (BMU), Gurugram, Haryana",
      "shaktikundu@gmail.com",
    ],
    [
      "5",
      "Prof. Suresh R. Jajoo",
      "Assistant Professor",
      "Datta Meghe College of Engineering (Mumbai University)",
      "suresh.jajoo@dmce.ac.in",
    ],
    [
      "6",
      "Dr. Penubaka Balaji",
      "Assistant Professor",
      "K L University, Guntur",
      "pbalaji@kluniversity.in",
    ],
    [
      "7",
      "MD Shamsul Haque Ansari",
      "Assistant Professor",
      "K L University, Vijayawada",
      "shamsshamsul@gmail.com",
    ],
    [
      "8",
      "Dr. M. Ravi Sankar",
      "Associate Professor",
      "K L University, Guntur",
      "mravisankar@kluniversity.in",
    ],
    [
      "9",
      "Dr. Abhishek Kumar Pandey",
      "Associate Professor",
      "Chandigarh University",
      "abhishek.e17100@cumail.in",
    ],
    [
      "10",
      "Dr. Preeti Khera",
      "Associate Professor",
      "Chandigarh University",
      "preeti.e17576@cumail.in",
    ],
    [
      "11",
      "Dr. Prabhjot Kaur",
      "Assistant Professor",
      "Chandigarh University",
      "prabhjot.e16646@cumail.in",
    ],
    [
      "12",
      "Dr. Richa Singh",
      "Assistant Professor",
      "KIET Group of Institutions, Ghaziabad",
      "rsrinet.876@gmail.com",
    ],
    [
      "13",
      "Dr. Gaurav Srivastav",
      "Assistant Professor",
      "KIET Group of Institutions, Ghaziabad",
      "gauravsrivastav2507@gmail.com",
    ],
    [
      "14",
      "Dr. Umang Garg",
      "Associate Professor and Research Coordinator",
      "MITADT University, Pune",
      "umangarg@gmail.com",
    ],
    [
      "15",
      "Basant Sah",
      "Associate Professor",
      "Koneru Lakshmaiah Education Foundation, Guntur, AP",
      "basantbitmtech2008@gmail.com",
    ],
    [
      "16",
      "Dr. Mahadev",
      "Associate Professor",
      "Chandigarh University",
      "Mahadev.agra@gmail.com",
    ],
    [
      "17",
      "Dr. Kapil Aggarwal",
      "Associate Professor",
      "Koneru Lakshmaiah Education Foundation, Vaddeswaram, Guntur District, AP",
      "kapil594@gmail.com",
    ],
    [
      "18",
      "Dr. Konatham Sumalatha",
      "Assistant Professor Sr. Gr",
      "School of Computer Science and Engineering, Vellore Institute of Technology",
      "konatham.sumalatha@vit.ac.in",
    ],
    [
      "19",
      "Dr. Krishna Kumar",
      "Professor",
      "Institute of Technology & Management, GIDA, Gorakhpur 273001",
      "kk_gkp@rediffmail.com",
    ],
    [
      "20",
      "Dr. Wasim Khan",
      "Assistant Professor",
      "KL University",
      "khanwasim051@gmail.com",
    ],
    [
      "21",
      "Priyajit Dash",
      "Assistant Professor",
      "Rajasthan Technical University, Kota",
      "dash.priyajit@gmail.com",
    ],
    [
      "22",
      "Dr. Anoop Kumar Tiwari",
      "Assistant Professor",
      "Department of Computer Science and IT, Central University of Haryana",
      "dranoop@cuh.ac.in",
    ],
    [
      "23",
      "Dr. Vinay Kumar Singh",
      "Professor",
      "Lovely Professional University",
      "vks.vinaykumarsingh@gmail.com",
    ],
    [
      "24",
      "Dr. Parul Datta",
      "Assistant Professor",
      "-",
      "parul.e17144@cumail.in",
    ],
    [
      "25",
      "Dr. Navjyot Kaur",
      "Assistant Professor",
      "Chandigarh University, Mohali",
      "navjyot16.kaur@gmail.com",
    ],
    [
      "26",
      "Dr. Raj Kumar",
      "Associate Professor",
      "Dept. of CSE, Chandigarh University",
      "rajshira@gmail.com",
    ],
    [
      "27",
      "Prof. Vineet Mehan",
      "Professor",
      "AIML Department, NIET, Nims University Rajasthan",
      "vineet.mehan@nimsuniversity.org",
    ],
    [
      "28",
      "Dr. Amit Kumar Goyal",
      "Professor",
      "Chandigarh University",
      "athroam@gmail.com",
    ],
    [
      "29",
      "Aneesh Kumar Mishra",
      "Assistant Professor CSE",
      "JECRCU, Jaipur",
      "aneeshjuetphdcse2k19@gmail.com",
    ],
    [
      "30",
      "Amit Verma",
      "Assistant Professor",
      "DR. K N Modi University, Rajasthan",
      "amit.cse@dknmu.org",
    ],
    [
      "31",
      "Dr. Vipin Jain",
      "Assistant Professor",
      "VIT Bhopal University",
      "er.vipinjain@gmail.com",
    ],
    [
      "32",
      "Rudramani Bhutia",
      "Assistant Professor",
      "Koneru Lakshmiah Educational Foundation (K L University)",
      "rudra.kuna@mail.com",
    ],
    [
      "33",
      "Dr. Sourav Pramanik",
      "Assistant Processor",
      "New Alipore College",
      "souravpramanik@newaliporecollege.ac.in",
    ],
    [
      "34",
      "Dr. Mudit Saxena",
      "Asst. Professor",
      "Teerthanker Mahaveer University, Moradabad",
      "mudit051285@gmail.com",
    ],
    [
      "35",
      "Dr. Bhavani Sankar Panda",
      "Professor & HoD AI ML",
      "Dept. of CSE, Raghu Engineering College (Autonomous), Vizianagaram, Andhra Pradesh",
      "bspanda.cse@gmail.com",
    ],
    [
      "36",
      "Asesh Kumar Tripathy",
      "Assistant Professor",
      "Dept. of CSE, KLEF-Deemed to be University, Vijayawada, Andhra Pradesh",
      "asesh.tripathy@gmail.com",
    ],
    [
      "37",
      "Dr. Raghwendra Kishore Singh",
      "Assistant Professor",
      "School of Computer Science & Artificial Intelligence, SR University, Warangal, Telangana",
      "raghwendra@sru.edu.in",
    ],
    [
      "38",
      "Dr. Pramoda Patro",
      "Associate Professor",
      "School of Computer Science & Artificial Intelligence, SR University, Warangal, Telangana",
      "Pramoda.patro@sru.edu.in",
    ],
    [
      "39",
      "Shanker Chandre",
      "Assistant Professor",
      "School of Computer Science & Artificial Intelligence, SR University, Warangal, Telangana",
      "Shanker.chandre@gmail.com",
    ],
    [
      "40",
      "Dr. Sasanko Sekhar Gantayat",
      "Associate Professor",
      "School of Computer Science & Artificial Intelligence, SR University, Warangal, Telangana",
      "s.gantayat@sru.edu.in",
    ],
    [
      "41",
      "Dr. Shubham Kumar",
      "Assistant Professor",
      "-",
      "shubham1d1kumar@gmail.com",
    ],
    [
      "42",
      "Prof. (Dr.) Kuldeep Tomar",
      "Professor-CSE & Dean Academics",
      "NGFCET, Affiliated to JC Bose University YMCA Faridabad",
      "drkuldeep2023@gmail.com",
    ],
    [
      "43",
      "Dr. Archana Sharma",
      "Professor",
      "Delhi Technical Campus, Greater Noida",
      "asharma12569@gmail.com",
    ],
    [
      "44",
      "Dr. Neha Jain",
      "HoD-AI and Associate Professor",
      "Delhi Technical Campus, Greater Noida",
      "nehajain312@gmail.com",
    ],
    [
      "45",
      "Dr. Gagan Tiwari",
      "Professor",
      "Noida International University",
      "Gagan.tiwari@niu.edu.in",
    ],
    [
      "46",
      "Dr. Deepika Sharma",
      "Assistant Professor",
      "Noida International University",
      "Deepika.sharma@niu.edu.in",
    ],
    [
      "47",
      "Dr. Rashmi Dahiya",
      "Assistant Professor",
      "Noida International University",
      "rashmi.dahiya@niu.edu.in",
    ],
    [
      "48",
      "Dr. Saurabh Kumar Pathak",
      "Assistant Professor",
      "Noida International University",
      "Saurabh.kumar1@niu.edu.in",
    ],
    [
      "49",
      "Dr. Ranjit Singh",
      "Associate Professor",
      "Chandigarh University",
      "Ranjit.e10947@cumail.in",
    ],
    [
      "50",
      "Dr. Aleem Ali",
      "Professor & Research Coordinator",
      "Dept. of CSE, Chandigarh University, Gharuan-Mohali, Punjab",
      "aleem.e12948@cumail.in",
    ],
    [
      "51",
      "Dr. Hardeep Singh",
      "Professor",
      "Amritsar Group of Colleges, Amritsar (Punjab), India",
      "geniussodhi@gmail.com",
    ],
    [
      "52",
      "Manikandan J",
      "Assistant Professor",
      "St. Joseph's College of Engineering",
      "jmanekandan@gmail.com",
    ],
    [
      "53",
      "Rohit Kumar Singh",
      "Assistant Professor",
      "Moradabad Institute of Technology",
      "rohitmtech1988@gmail.com",
    ],
    [
      "54",
      "Dr. Shipra Srivastava",
      "Associate Professor",
      "Greater Noida Institute of Technology, Greater Noida",
      "shipra.iot@gniot.net.in",
    ],
    [
      "55",
      "Er. Bikram Pal Singh",
      "Deputy Dean (Training & Placements)",
      "Global Group of Institutes, Amritsar (Punjab)",
      "bikram.2k2@gmail.com",
    ],
    [
      "56",
      "Dr. Santosh Rane",
      "President, IIC SPCE Mumbai",
      "Sardar Patel College of Engineering, Mumbai",
      "s_rane@spce.ac.in",
    ],
    [
      "57",
      "Dr. Ajay Indian",
      "Assistant Professor",
      "Central University of Rajasthan, Ajmer-305817",
      "ajay.indian@curaj.ac.in",
    ],
    [
      "58",
      "Dr. Gaurav Meena",
      "Assistant Professor",
      "Central University of Rajasthan, Ajmer-305817",
      "gaurav.meena@curaj.ac.in",
    ],
    [
      "59",
      "Dr. Jaspreet Singh Batth",
      "Professor and Head",
      "Department of CSE, Chandigarh University",
      "jaspreet.e10279@cumail.in",
    ],
    [
      "60",
      "Dr. Shailesh Saxena",
      "Associate Professor & Dean Academics",
      "SRMS College of Engineering and Technology, Bareilly UP",
      "shailesh.saxena@srms.ac.in",
    ],
    [
      "61",
      "Prof. (Dr.) Brijesh Kumar Chaurasia",
      "Dean, Research & Innovation",
      "Pranveer Singh Institute of Technology, Kanpur",
      "deanresearch@psit.ac.in, brijeshchaurasia@ieee.org",
    ],
    [
      "62",
      "Dr. Rahul Rastogi",
      "Associate Professor & Director",
      "Rakshpal Bhadur College of Engineering & Technology, Bareilly UP",
      "rahulrastogi6@gmail.com",
    ],
    [
      "63",
      "Dr. Anil Kumar Bisht",
      "Assistant Professor, CS & IT Deptt, FET",
      "MJPRU, Bareilly, U.P",
      "anil.bisht@mjpru.ac.in",
    ],
    [
      "64",
      "Dr. Sukhpreet Singh",
      "Assistant Professor",
      "AIT CSE, Chandigarh University",
      "sukhis005@gmail.com",
    ],
    [
      "65",
      "Dr. Jayant R. Nandwalkar",
      "Assistant Professor",
      "Datta Meghe College of Engineering",
      "10jnand@gmail.com",
    ],
    [
      "66",
      "Prof. (Dr.) Tanmoy Som",
      "Professor",
      "Department of Mathematical Sciences, IIT(BHU), Varanasi",
      "tsom.apm@iitbhu.ac.in",
    ],
    [
      "67",
      "Dr. Ashish Khaira",
      "Assistant Professor",
      "Symbiosis University of Applied Sciences, Indore",
      "ashish.khaira@suas.ac.in",
    ],
    [
      "68",
      "Dr. Rohini Raina",
      "Assistant Professor",
      "G.L.A University",
      "rohini.raina@gla.ac.in",
    ],
    [
      "69",
      "Shuchita Mudgil",
      "Sr. Lecturer IT",
      "Kalaniketan Polytechnic College, Jabalpur, Madhya Pradesh",
      "shuchitamudgil@gmail.com",
    ],
    [
      "70",
      "Amit Kumar",
      "Assistant Professor",
      "CCSIT, Teerthankar Mahaveer University, Moradabad",
      "amitakg84@gmail.com",
    ],
    [
      "71",
      "Dr. Partha Pakray",
      "Associate Professor",
      "NIT Silchar",
      "partha@cse.nits.ac.in",
    ],
    [
      "72",
      "Dr. Ranjita Das",
      "Assistant Professor",
      "NIT Agartala",
      "ranjita.nitm@gmail.com",
    ],
    [
      "73",
      "Dr. Dipanwita Debnath",
      "Assistant Professor",
      "Koneru Lakshmaiah Education Foundation",
      "ddebnath.nita@gmail.com",
    ],
    [
      "74",
      "Dr. Varun Srivastava",
      "Assistant Professor",
      "Jaypee Institute of Information Technology, Noida",
      "varun.srivastava@mail.jiit.ac.in",
    ],
    [
      "75",
      "Dr. Shelendra Pal",
      "Assistant Professor",
      "Jaypee Institute of Information Technology, Noida",
      "shelendra.pal@jiit.ac.in",
    ],
    [
      "76",
      "Dr. Anuj Jain",
      "Professor",
      "Department of Computer Science and Engineering, Chandigarh University, Punjab, India",
      "anuj.e17635@cumail.in",
    ],
    [
      "77",
      "Dr. Sumanta Kumar Mohapatra",
      "Assistant Professor",
      "Trident Academy of Technology, BPUT, Odisha",
      "sumsusmeera@gmail.com",
    ],
    [
      "78",
      "Dr. Yogesh Kumar Sharma",
      "Assistant Professor",
      "Koneru Lakshmaiah Education Foundation (KL Deemed to be University)",
      "dr.sharmayogeshkumar@gmail.com",
    ],
    [
      "79",
      "Dr. Madan Lal Saini",
      "Professor",
      "Chandigarh University",
      "madan.e13485@cumail.in",
    ],
    [
      "80",
      "Dr. Rashmi Soni",
      "Associate Professor ISE & Research Supervisor CSE",
      "-",
      "drrashmicseofficial@gmail.com",
    ],
    [
      "81",
      "Dr. Nancy Arya",
      "Associate Professor",
      "G D Goenka University, Gurugram",
      "nancy.arya@gdgu.org",
    ],
    [
      "82",
      "Dr. Vijay Bhardwaj",
      "Professor",
      "AIT CSE, Chandigarh University",
      "prof.dr.bhardwaj@gmail.com",
    ],
    [
      "83",
      "Dr. Anil Kumar",
      "Assistant Professor",
      "GLA University",
      "frequencyanil@gmail.com",
    ],
    [
      "84",
      "Dr. KM Baalamurugan",
      "Assistant Professor",
      "IILM University, Greater Noida, India",
      "baalaresearch@outlook.com",
    ],
    [
      "85",
      "Dr. Ratnesh Kumar Dubey",
      "Assistant Professor",
      "IILM University, Greater Noida, India",
      "ratnesh.soet@itmuniversity.ac.in",
    ],
    [
      "86",
      "Dr. C. Ramesh Kumar",
      "Associate Professor",
      "Galgotias University, Greater Noida, UP, India",
      "c.ramesh@galgotiasuniversity.edu.in",
    ],
    [
      "87",
      "Dr. Pragya Jain",
      "Assistant Professor",
      "ITM University, Gwalior, India",
      "pragyajain.cse@itmuniversity.ac.in",
    ],
    [
      "88",
      "Dr. Aravendra Kumar Sharma",
      "Assistant Professor",
      "ITM University, Gwalior, India",
      "aravendra.cse@itmuniversity.ac.in",
    ],
    [
      "89",
      "Dr. Pragya",
      "Assistant Professor",
      "Galgotias University, Greater Noida, UP, India",
      "agrawal.pragya11@gmail.com",
    ],
    [
      "90",
      "Dr.S.Rajalakshmi",
      "Professor",
      "Dr.N.G.P. Institute of Technology, Coimbatore, India",
      "mrajislm@gmail.com",
    ],
    [
      "91",
      "Dr.A.S.Shanthi",
      "Associate Professor",
      "Dr.N.G.P. Institute of Technology, Coimbatore, India",
      "babushanthi@gmail.com",
    ],
    [
      "92",
      "Dr Prithi Samuel",
      "Assistant Professor",
      "SRM Institute of Science and Technology, Kattankulathur, Chengalpattu, India",
      "drprithisamuel@gmail.com",
    ],
    [
      "93",
      "Dr. M Kiruthika",
      "Assistant Professor",
      "SRM Institute of Science and Technology, Kattankulathur, Chengalpattu, India",
      "kiruthim4@srmist.edu.in",
    ],
    [
      "94",
      "Dr. Vijay K",
      "Assistant Professor SG",
      "Rajalakshmi Engineering College, Chennai, India",
      "vijay.k@rajalakshmi.edu.in",
    ],
    [
      "95",
      "Dr. Rajkumar Rajavel",
      "Associate Professor & Honors Coordinator",
      "School of Engineering and Technology, Department of Computer Science and Engineering, CHRIST (Deemed to be University), Bangalore, Karnataka-560074, India",
      "rajkumarprt@gmail.com",
    ],
    [
      "96",
      "Dr. Ragini Kumari",
      "Assistant Professor",
      "Manav Rachna International Institute of Research and Studies, Faridabad, Haryana, India",
      "raginikumari.set@mriu.edu.in",
    ],
    [
      "97",
      "Dr. Shobha Tyagi",
      "Associate Professor",
      "Manav Rachna International Institute of Research and Studies, Faridabad, Haryana, India",
      "tyagishobha.set@mriu.edu.in",
    ],
    [
      "98",
      "Dr. T.N Prabhu",
      "Assistant Professor (Selection Grade)",
      "Department of Information Technology, Dr. NGP Institute of Technology, Coimbatore, India",
      "prabhu.tn@drngpit.ac.in",
    ],
    [
      "99",
      "Dr. P Sivaprakash",
      "Associate Professor",
      "Department of Computer Science and Business Systems, Dr. N.G.P. Institute of Technology, Coimbatore, India",
      "sivaprakashcse0402@gmail.com",
    ],
    [
      "100",
      "Dr Mohankumar B",
      "Assistant Professor",
      "School of Computer Science and Engineering (SCOPE), Vellore Institute of Technology, Vellore, Tamilnadu, India",
      "mohankumar.b@vit.ac.in",
    ],
    [
      "101",
      "Dr. R. Pitchai",
      "Associate Professor",
      "B V Raju Institute of Technology, Narsapur, India",
      "ramasamy.p@bvrit.ac.in",
    ],
    [
      "102",
      "Dr. V.Praveena",
      "Associate Professor",
      "Dr. NGP Institute of Technology, Coimbatore, Tamil Nadu, India",
      "drvpraveena@gmail.com",
    ],
    [
      "103",
      "Dr. R. Priscilla Joy",
      "Assistant Professor",
      "Karunya Institute of Technology and Sciences, Coimbatore, Tamil Nadu, India",
      "priscillajoy@karunya.edu",
    ],
    [
      "104",
      "Mr.S.Dinesh Krishnan",
      "Assistant Professor",
      "B V Raju Institute of Technology, Narsapur, India",
      "dinesh.krishnan@bvrit.ac.in",
    ],
    [
      "105",
      "Dr. R.Renugadevi",
      "Associate Professor",
      "Saveetha Engineering College, Tamil Nadu, India",
      "renubalume@gmail.com",
    ],
    [
      "106",
      "Dr. S. Shankar",
      "Professor and Head",
      "Hindusthan College of Engineering and Technology, affiliated to Anna University, Coimbatore, India",
      "csehod@hicet.ac.in",
    ],
    [
      "107",
      "Dr. G S Pradeep Ghantasala",
      "Professor",
      "Alliance University, Karnataka, India",
      "ggspradeep@gmail.com",
    ],
    [
      "108",
      "Dr.Vijay Ramalingam",
      "Assistant Professor",
      "Sathyabama Institute of Science and Technology, Tamil Nadu, India",
      "vijayrscs@gmail.com",
    ],
    [
      "109",
      "Dr. M Amutha Prabakar",
      "Assistant Professor",
      "Department of Computer Engineering, Government Polytechnic College, Perambalur, Tamil Nadu, India",
      "amuthaprabakar.m.phd@gmail.com",
    ],
    [
      "110",
      "Dr.A.Hemlathadhevi",
      "Professor",
      "Panimalar Engineering College, Tamil Nadu, India",
      "hemlathadhevi@gmail.com",
    ],
    [
      "111",
      "Dr. Nidhi Dandotiya",
      "Associate Professor",
      "ITM University, Gwalior, India",
      "nidhidandotiya@itmuniversity.ac.in",
    ],
    [
      "112",
      "Dr Janarthanan Sekar",
      "Assistant Professor",
      "Jain (Deemed-to-be University), Bengaluru, India",
      "jana.mkce@gmail.com",
    ],
    [
      "113",
      "Dr Nilesh Jain",
      "Associate Professor",
      "Mandsaur University, Mandsaur, Madhya Pradesh, India",
      "Nilesh.jain@meu.edu.in",
    ],
    [
      "114",
      "Dr. Surendra Kumar",
      "Assistant Professor",
      "GLA University, Mathura, India",
      "kumar.surendra1989@gmail.com",
    ],
    [
      "115",
      "DR. SATYA PRAKASH YADAV",
      "Assistant Professor",
      "GL Bajaj Institute of Technology and Management, Greater Noida, India",
      "prakashyadav.satya@gmail.com",
    ],
    [
      "116",
      "Dr. JAGJIT SINGH DHATTERWAL",
      "Associate Professor",
      "Koneru Lakshmaiah Education Foundation, Vaddeswaram, Guntur District, Andhra Pradesh-522302, India",
      "jagjits247@gmail.com",
    ],
    [
      "117",
      "Dr. PRIYANKA DATTA",
      "Assistant Professor",
      "Chitkara University, Rajpura, Punjab, India",
      "priyanka.datta@chitkara.edu.in",
    ],
    [
      "118",
      "Dr Ashish Srivastava",
      "Assistant Professor",
      "GLA University, Mathura, Uttar Pradesh, India",
      "ashish.srvstava88@gmail.com",
    ],
    [
      "119",
      "Dr. Arul Prakash",
      "Assistant Professor",
      "Sathyabama Institute of Science and Technology, Tamil Nadu, India",
      "prakash875@gmail.com",
    ],
    [
      "120",
      "Dr. Madhav",
      "Assistant Professor",
      "Poornima University, Jaipur, India",
      "madhavsharma36@yahoo.co.in",
    ],
    [
      "121",
      "Dr. Savita",
      "Assistant Professor",
      "The Indian Institute of Technology, Bombay, India",
      "savitakashyap473@gmail.com",
    ],
    [
      "122",
      "Dr. Gourav",
      "Assistant Professor",
      "IILM University, Greater Noida, India",
      "gourav.sharma@iilm.edu",
    ],
    [
      "123",
      "Dr. Subhajit",
      "Assistant Professor",
      "IMS Engineering College, Ghaziabad, Uttar Pradesh, India",
      "professor.sghosh@gmail.com",
    ],
    [
      "124",
      "Dr. Dineshkumar",
      "Assistant Professor",
      "Kongunadu College of Engineering and Technology, Tholurpatti, Tamil Nadu, India",
      "dineshrajumanibe@gmail.com",
    ],
    [
      "125",
      "Dr. Nikhil",
      "Assistant Professor",
      "Sharda University, Knowledge Park III, Greater Noida, Uttar Pradesh, India",
      "nrcs008@gmail.com",
    ],
    [
      "126",
      "Dr. Pooja",
      "Assistant Professor",
      "Nirma University, Ahmedabad, Gujarat, India",
      "chaturvedi.pooja03@gmail.com",
    ],
    [
      "127",
      "Dr. Venkatesan",
      "Assistant Professor",
      "Paavai Engineering College, Tamil Nadu, India",
      "balavenkatbe@gmail.com",
    ],
    [
      "128",
      "Dr.Amit Kumar",
      "Assistant Professor",
      "Amity University, Rajasthan, India",
      "amit79668@gmail.com",
    ],
    [
      "129",
      "Dr. Keerthana",
      "Assistant Professor",
      "K.S.R. College of Engineering, Tamil Nadu, India",
      "keerthiksrcecse@gmail.com",
    ],
    [
      "130",
      "Dr. Ramya",
      "Assistant Professor",
      "Kamaraj College of Engineering and Technology, Madurai, India",
      "ramyaranjithsingh@gmail.com",
    ],
    [
      "131",
      "Dr. Rakesh",
      "Assistant Professor",
      "C.V. Raman Global University, Odisha, India",
      "rakeshranjan@cgu-odisha.ac.in",
    ],
    [
      "132",
      "Dr. Richa",
      "Assistant Professor",
      "Bennett University, Greater Noida, Uttar Pradesh, India",
      "richa.golash@bennett.edu.in",
    ],
    [
      "133",
      "Dr. Sheeja",
      "Assistant Professor",
      "Easwari Engineering College, Tamil Nadu, India",
      "r.sheeja@eec.srmrmp.edu.in",
    ],
    [
      "134",
      "Dr. Ravi Kumar",
      "Assistant Professor",
      "Jaypee University of Engineering & Technology, Madhya Pradesh, India",
      "ravi.kumar6@gmail.com",
    ],
    [
      "135",
      "Dr. Abhishek Singhal",
      "Assistant Professor",
      "Amity University, Noida, India",
      "abhi087@gmail.com",
    ],
    [
      "136",
      "Dr. Bhawna Narwal",
      "Assistant Professor",
      "Indira Gandhi Delhi Technical University for Women, Delhi, India",
      "bhawnanarwal@gmail.com",
    ],
    [
      "137",
      "Dr. Varun Shukla",
      "Assistant Professor",
      "Pranveer Singh Institute of Technology, Kanpur, Uttar Pradesh, India",
      "varun.shuklaa@gmail.com",
    ],
    [
      "138",
      "Dr. Rakesh K.Bajaj",
      "Assistant Professor",
      "JAYPEE UNIVERSITY OF INFORMATION TECHNOLOGY, WAKNAGHAT, SOLAN (HP), India",
      "rakesh.bajaj@juitsolan.in",
    ],
    [
      "139",
      "Dr. Atul Kumar",
      "Assistant Professor",
      "Maharana Pratap Group of Institutions, Kanpur, India",
      "atulverma16@gmail.com",
    ],
    [
      "140",
      "Dr. Altaf Multani",
      "Assistant Professor",
      "SKN Sinhgad College of Engg., Pandharpur, India",
      "draomulani.vlsi@gmail.com",
    ],
    [
      "141",
      "Dr. Arpita Singh",
      "Assistant Professor",
      "Amity University, Noida, India",
      "singharpita999@gmail.com",
    ],
    [
      "142",
      "Dr. Monika Sharma",
      "Assistant Professor",
      "NMIMS Deemed-to-be-University, Maharashtra, India",
      "monika.sharma@nmims.edu",
    ],
    [
      "143",
      "Dr. Asha Rawat",
      "Assistant Professor",
      "NMIMS Deemed-to-be-University, Maharashtra, India",
      "asha.rawat@nmims.edu",
    ],
    [
      "144",
      "Dr. Shahjahan Ali",
      "Assistant Professor",
      "SRMS CET, Bareilly, India",
      "shahjahansrms@gmail.com",
    ],
    [
      "145",
      "Dr. Aravind Mohan",
      "Data scientist, Quantified-self enthusiast, Human",
      "California, United States",
      "ara.mohan@gmail.com",
    ],
    [
      "146",
      "Dr. Makarand Jadhav",
      "Assistant Professor",
      "Sinhgad Institute, Maharashtra, India",
      "makarandjadhav189@gmail.com",
    ],
    [
      "147",
      "Dr. Hem Dutt Joshi",
      "Assistant Professor",
      "Thapar University, Punjab, India",
      "hemdutt.joshi@thapar.edu",
    ],
    [
      "148",
      "Dr. Prakash Srivastava",
      "Assistant Professor",
      "Graphic Era (Deemed to be University), Dehradun, India",
      "prakash2418@gmail.com",
    ],
    [
      "149",
      "Dr. Akash Sanghi",
      "Assistant Professor",
      "Invertis University, Uttar Pradesh, India",
      "akash.s@invertis.org",
    ],
    [
      "150",
      "Dr. Pooja Singh",
      "Assistant Professor",
      "Galgotias University, Uttar Pradesh, India",
      "pooja17ps@gmail.com",
    ],
    [
      "151",
      "Dr. Meeta Chaudhary",
      "Assistant Professor",
      "ABES Engineering College, Ghaziabad, Uttar Pradesh, India",
      "meetag2@gmail.com",
    ],
    [
      "152",
      "Dr. Milind Bhatt",
      "Assistant Professor",
      "Maharana Pratap Engineering College, Kanpur, Uttar Pradesh, India",
      "bhattmilind@gmail.com",
    ],
    [
      "153",
      "Dr. Pooja Jha",
      "Assistant Professor",
      "Amity University, Ranchi, India",
      "pooja2905@gmail.com",
    ],
    [
      "154",
      "Dr. Gaurav Agarwal",
      "Associate Professor",
      "Invertis University, Bareilly, UP, India",
      "gaurav.a1@invertis.org",
    ],
    [
      "155",
      "Dr. Arati Kushwaha",
      "Associate Professor",
      "Department of Computer Science, Allahabad Degree College, University of Allahabad, Prayagraj, India",
      "aratikushwaha.jk@gmail.com",
    ],
    [
      "156",
      "Dr. Amit Pimpalkar",
      "Assistant Professor",
      "Ramdeobaba University, Nagpur, India",
      "pimpalkarap@rknec.edu",
    ],
    [
      "157",
      "Dr. Ravi Sharma",
      "Associate Professor",
      "Galgotias University, Greater Noida, India",
      "ravi.cs.0904@gmail.com",
    ],
    [
      "158",
      "Dr Kirti Shukla",
      "Associate Professor",
      "School of Computer Science and Engineering, IILM University, Greater Noida, India",
      "kirti.shukla@iilm.edu",
    ],
    [
      "159",
      "Dr Amit Shukla",
      "Associate Professor",
      "IIMT College of Engineering, Knowledge Park, Greater Noida, Uttar Pradesh, India",
      "shuklaamitamitshukla@gmail.com",
    ],
  ];

  const TableHeader = ({ headers }) => (
    <thead className="bg-emerald-600 text-white">
      <tr>
        {headers.map((header, index) => (
          <th
            key={index}
            className="px-4 py-3 text-left font-bold border border-gray-200"
          >
            {header}
          </th>
        ))}
      </tr>
    </thead>
  );

  const TableBody = ({ rows }) => (
    <tbody>
      {rows.map((row, rowIndex) => (
        <tr key={rowIndex} className="hover:bg-gray-100 even:bg-gray-50">
          {row.map((cell, cellIndex) => (
            <td key={cellIndex} className="px-4 py-3 border border-gray-200">
              {cell}
            </td>
          ))}
        </tr>
      ))}
    </tbody>
  );

  return (
    <div className="container mx-auto px-4 mt-20">
      <h1 className="text-4xl font-bold text-gray-700 mb-6 text-center">
        Technical Committee
      </h1>
      <div className="overflow-x-auto">
        <table className="min-w-full bg-white border border-gray-200 shadow-sm rounded-lg">
          <TableHeader headers={csvData[0]} />
          <TableBody rows={csvData.slice(1)} />
        </table>
      </div>
    </div>
  );
};

export default TechnicalCommittee;
